language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml